#!/bin/bash

if [[ $# == 0 ]]; then
		printf "Need at least 1 positional argument. Use --help to see instructions."
		exit 1
fi

#Rename the forward and reverse for later use
if [[ $1 == '-h' ]] || [[ $1 == '--help' ]]; then
	printf "\tPositional parameter 1: read1, Positional parameter 2: read2\n"
	#printf "\t-trim: ONLY trim the adapters with default settings\n"
	exit 0
fi

#Cutadapt TWO ROUNDS to cut adapters
trim() {
	cutadapt -f fastq --match-read-wildcards --times 1 -e 0.1 -O 1 --quality-cutoff 6 -m 18 -a NNNNNAGATCGGAAGAGCACACGTCTGAACTCCAGTCAC -g CTTCCGATCTACAAGTT -g CTTCCGATCTTGGTCCT -A AACTTGTAGATCGGA -A AGGACCAAGATCGGA -A ACTTGTAGATCGGAA -A GGACCAAGATCGGAA -A CTTGTAGATCGGAAG -A GACCAAGATCGGAAG -A TTGTAGATCGGAAGA -A ACCAAGATCGGAAGA -A TGTAGATCGGAAGAG -A CCAAGATCGGAAGAG -A GTAGATCGGAAGAGC -A CAAGATCGGAAGAGC -A TAGATCGGAAGAGCG -A AAGATCGGAAGAGCG -A AGATCGGAAGAGCGT -A GATCGGAAGAGCGTC -A ATCGGAAGAGCGTCG -A TCGGAAGAGCGTCGT -A CGGAAGAGCGTCGTG -A GGAAGAGCGTCGTGT -o R1.fastq.gz.adapterTrim.fastq.gz -p R2.fastq.gz.adapterTrim.fastq.gz $FILE1 $FILE2 > R1.fastq.gz.adapterTrim.metrics
	cutadapt -f fastq --match-read-wildcards --times 1 -e 0.1 -O 5 --quality-cutoff 6 -m 18 -A AACTTGTAGATCGGA -A AGGACCAAGATCGGA -A ACTTGTAGATCGGAA -A GGACCAAGATCGGAA -A CTTGTAGATCGGAAG -A GACCAAGATCGGAAG -A TTGTAGATCGGAAGA -A ACCAAGATCGGAAGA -A TGTAGATCGGAAGAG -A CCAAGATCGGAAGAG -A GTAGATCGGAAGAGC -A CAAGATCGGAAGAGC -A TAGATCGGAAGAGCG -A AAGATCGGAAGAGCG -A AGATCGGAAGAGCGT -A GATCGGAAGAGCGTC -A ATCGGAAGAGCGTCG -A TCGGAAGAGCGTCGT -A CGGAAGAGCGTCGTG -A GGAAGAGCGTCGTGT -o r1.adapterTrim.round2.fastq.gz -p r2.adapterTrim.round2.fastq.gz R1.fastq.gz.adapterTrim.fastq.gz R2.fastq.gz.adapterTrim.fastq.gz > R1.fastq.gz.adapterTrim.round2.metrics
}

if [[ $1 == '-trim' ]]; then
	FILE1=$2
	FILE2=$3
	trim
	exit 0
fi

if [[ $# == 2 ]]; then
	FILE1=$1
	FILE2=$2
	trim
	exit 0
fi